spring:
  kafka:
    consumer:
      topic: test-topic
      bootstrap-servers: localhost:9092
      auto-offset-reset: latest
      enable-auto-commit: true
      group-prefix: sample

    consumer-group: topic
    producer:
      bootstrap-servers: localhost:9092

    schema:
      registry:
        url: http://localhost:8081

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12rating_app!@


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect